import type { Metadata } from "next";
import "../styles/globals.css";
import Providers from "@/lib/providers"
import { store } from "@/lib/store";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers store={store}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
